### ISSUE TITLE
h-e-l-p

### ISSUE THREAD

**Issue by userguazi** [rentainhe/visualization#10]
可视化自己的图片时总是报这样的错，我都把宽和高写死了还是报这个错怎么办呀
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/resize.cpp:3699: error: (-215:Assertion failed) !dsize.empty() in function 'resize'

**Comment by rentainhe** [comment]
你可以考虑重新安装一下cv2这个库

**Comment by rentainhe** [comment]
I'm going to close this issue, feel free to reopen it if needed
