### ISSUE TITLE
你好，请问使用run_grid_attention_example(version=2），产生如下图片，注意力图是彩色波纹，是啥原因，怎么解决？

### ISSUE THREAD

**Issue by looker23333** [rentainhe/visualization#3]
![version2_example_without_attention_with_attention](https://user-images.githubusercontent.com/48302705/135721542-f2ef617c-72ea-4ebb-af5b-1d3071aa3c35.jpg)

**Comment by rentainhe** [comment]
@looker23333 这是因为里面的一个参数cmap决定的，这是比较好看的一种热力图，红色的值表示attention关注的位置比较高的区域，然后因为默认设置的其实是随机生成的没有归一化后的一个attention map用来举例，所以可能看起来就比较奇怪一点，是正常现象，我之后会增加一个vision transformer的example，会更好看一些

**Comment by rentainhe** [comment]
![example_with_attention](https://user-images.githubusercontent.com/48727989/135739236-480daf8c-4fa7-4c46-8f86-8323e2648888.jpg)
这样的图是不是更加直观一些，我已经更新了[example.py](https://github.com/rentainhe/visualization/blob/f21e12472740eb81e2061c326968bc7bfa06c743/example.py#L32)，主要的区别就是，把随机生成的attention mask给归一化了

**Comment by looker23333** [comment]
懂了，谢谢
