### ISSUE TITLE
About Grid Attention Visualization

### ISSUE THREAD

**Issue by aichisuancai** [rentainhe/visualization#5]
非常感谢你能开源如此有趣的代码！在你 Usage 部分中，https://github.com/rentainhe/visualization/blob/master/visualize/region_attention_visualization 打不开，我得到的是 404 界面。请问是我的网络出现了问题，还是你在对这个页面进行修改，导致目前无法浏览？

**Comment by rentainhe** [comment]
> 非常感谢你能开源如此有趣的代码！在你 Usage 部分中，https://github.com/rentainhe/visualization/blob/master/visualize/region_attention_visualization 打不开，我得到的是 404 界面。请问是我的网络出现了问题，还是你在对这个页面进行修改，导致目前无法浏览？

这边我好像可以从网页访问，如果打开是404的话，可以检查一下是不是网络问题~

**Comment by rentainhe** [comment]
> 非常感谢你能开源如此有趣的代码！在你 Usage 部分中，https://github.com/rentainhe/visualization/blob/master/visualize/region_attention_visualization 打不开，我得到的是 404 界面。请问是我的网络出现了问题，还是你在对这个页面进行修改，导致目前无法浏览？

问题解决了吗～

**Comment by aichisuancai** [comment]
不好意思，昨天事情有点多，没有及时回复。昨天复制链接错了，是这个链接打不开https://github.com/rentainhe/visualization/tree/master/visualize_attention_map
![image](https://user-images.githubusercontent.com/94879248/144349966-11820d55-41f0-436a-8699-51a2a170a22f.png)

**Comment by rentainhe** [comment]
> 不好意思，昨天事情有点多，没有及时回复。昨天复制链接错了，是这个链接打不开https://github.com/rentainhe/visualization/tree/master/visualize_attention_map ![image](https://user-images.githubusercontent.com/94879248/144349966-11820d55-41f0-436a-8699-51a2a170a22f.png)

喔喔，是我这边忘记及时更新地址啦，非常感谢发现问题~~，现在已经更新好啦~~
