### ISSUE TITLE
visualization 0.6.0 Plan

### ISSUE THREAD

**Issue by rentainhe** [rentainhe/visualization#6]
## Visualization 0.6.0 TODO List
- [ ] Add Patchfiy Image and Compose Image Func
- [ ] Add Visualize BBox Func

## Reference
- https://www.cnblogs.com/zgqcn/p/10963356.html
- https://github.com/open-mmlab/mmcv/blob/master/mmcv/visualization/image.py
- https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.image.extract_patches_2d.html
- https://towardsdatascience.com/efficiently-splitting-an-image-into-tiles-in-python-using-numpy-d1bf0dd7b6f7

**Comment by zlj63501** [comment]
Visualization 0.7.0
Suggestion: Add a language 1D attention visualization.

**Comment by rentainhe** [comment]
> Visualization 0.7.0 Suggestion: Add a language 1D attention visualization.

Thanks for your advice~
